Tiramisu Optimization Framework: tiramisu::global Class Reference
tiramisu::global Class Reference
A class that holds all the global variables necessary for Tiramisu.
#include <expr.h>
Public Member Functions
global ()
Static Public Member Functions
static void set_auto_data_mapping (bool v)
If this option is set to true, Tiramisu automatically modifies the computation data mapping whenever a new schedule is applied to a computation.
static bool is_auto_data_mapping_set ()
Return whether auto data mapping is set.
static void set_loop_iterator_default_data_type (primitive_t type)
static primitive_t get_loop_iterator_default_data_type ()
static void set_default_tiramisu_options ()
Detailed Description
A class that holds all the global variables necessary for Tiramisu.
It also holds Tiramisu options.
Definition at line 44 of file expr.h.
Constructor & Destructor Documentation
global()
tiramisu::global::global () inline
Definition at line 102 of file expr.h.
References set_default_tiramisu_options().
Member Function Documentation
get_loop_iterator_default_data_type()
static primitive_t tiramisu::global::get_loop_iterator_default_data_type () inline static
Definition at line 84 of file expr.h.
is_auto_data_mapping_set()
static bool tiramisu::global::is_auto_data_mapping_set () inline static
Return whether auto data mapping is set.
If auto data mapping is set, Tiramisu automatically modifies the computation data mapping whenever a new schedule is applied to a computation. If it is set to false, it is up to the user to set the right data mapping before code generation.
Definition at line 74 of file expr.h.
set_auto_data_mapping()
static void tiramisu::global::set_auto_data_mapping (bool v) inline static
If this option is set to true, Tiramisu automatically modifies the computation data mapping whenever a new schedule is applied to a computation.
If it is set to false, it is up to the user to set the right data mapping before code generation.
Definition at line 61 of file expr.h.
Referenced by set_default_tiramisu_options().
set_default_tiramisu_options()
static void tiramisu::global::set_default_tiramisu_options () inline static
Examples:
tutorials/tutorial_01.cpp, tutorials/tutorial_02.cpp, tutorials/tutorial_03.cpp, tutorials/tutorial_04.cpp, tutorials/tutorial_05.cpp, and tutorials/tutorial_06.cpp.
Definition at line 89 of file expr.h.
References tiramisu::p_int32, tiramisu::p_int64, set_auto_data_mapping(), and set_loop_iterator_default_data_type().
Referenced by global().
set_loop_iterator_default_data_type()
static void tiramisu::global::set_loop_iterator_default_data_type (primitive_t type) inline static
Examples:
tutorials/tutorial_01.cpp, tutorials/tutorial_02.cpp, tutorials/tutorial_03.cpp, tutorials/tutorial_04.cpp, tutorials/tutorial_05.cpp, and tutorials/tutorial_06.cpp.
Definition at line 79 of file expr.h.
Referenced by set_default_tiramisu_options().
The documentation for this class was generated from the following file:
expr.h