Tiramisu Optimization Framework: tiramisu Namespace Reference
tiramisu Namespace Reference
Classes
class buffer
A class that represents buffers.
struct caster
struct caster< expr >
struct caster< var >
class computation
A class that represents computations.
class constant
A class that represents loop invariants.
class expr
A class to represent tiramisu expressions.
class function
A class to represent functions in Tiramisu.
class generator
A class for code generation.
class global
A class that holds all the global variables necessary for Tiramisu.
struct HalideCodegenOutput
class utility
A class containing utility functions.
class var
A class that represents constant variable references.
Enumerations
enum expr_t { e_val, e_var, e_op, e_none }
The possible types of an expression.
enum primitive_t {
p_uint8, p_uint16, p_uint32, p_uint64,
p_int8, p_int16, p_int32, p_int64,
p_float32, p_float64, p_boolean, p_none
}
tiramisu data types.
enum op_t {
o_minus, o_floor, o_sin, o_cos,
o_tan, o_asin, o_acos, o_atan,
o_abs, o_sqrt, o_expo, o_log,
o_ceil, o_round, o_trunc, o_allocate,
o_free, o_cast, o_address, o_add,
o_sub, o_mul, o_div, o_mod,
o_logical_and, o_logical_or, o_logical_not, o_eq,
o_ne, o_le, o_lt, o_ge,
o_gt, o_max, o_min, o_right_shift,
o_left_shift, o_select, o_cond, o_lerp,
o_call, o_access, o_none
}
Types of tiramisu operators.
enum argument_t { a_input, a_output, a_temporary }
Types of function arguments.
Functions
HalideCodegenOutput halide_pipeline_to_tiramisu_function (Halide::Internal::Stmt s, const std::vector< Halide::Internal::Function > &outputs, const std::map< std::string, Halide::Internal::Function > &env, const std::map< std::string, std::vector< int32_t >> &output_buffers_size, tiramisu::function *func)
void halide_stmt_dump (Halide::Internal::Stmt s)
Halide::Module lower_halide_pipeline (const std::string &pipeline_name, const Halide::Target &t, const std::vector< Halide::Argument > &args, const Halide::Internal::LoweredFunc::LinkageType linkage_type, Halide::Internal::Stmt s)
int loop_level_into_dynamic_dimension (int level)
int loop_level_into_static_dimension (int level)
std::string generate_new_variable_name ()
std::string str_from_tiramisu_type_expr (tiramisu::expr_t type)
std::string str_tiramisu_type_op (tiramisu::op_t type)
std::string str_from_tiramisu_type_primitive (tiramisu::primitive_t type)
Halide::Expr halide_expr_from_tiramisu_expr (const tiramisu::computation *comp, std::vector< isl_ast_expr *> &index_expr, const tiramisu::expr &tiramisu_expr)
Convert a Tiramisu expression into a Halide expression.
Halide::Type halide_type_from_tiramisu_type (tiramisu::primitive_t type)
Convert a Tiramisu type into the equivalent Halide type (if it exists), otherwise show an error message (no automatic type conversion is performed).
tiramisu::primitive_t halide_type_to_tiramisu_type (Halide::Type type)
Convert a Halide type into the equivalent Tiramisu type (if it exists), otherwise show an error message (no automatic type conversion is performed).
Enumeration Type Documentation
argument_t
enum tiramisu::argument_t
Types of function arguments.
"a_" stands for argument.
Enumerator
a_input
a_output
a_temporary
Definition at line 116 of file type.h.
expr_t
enum tiramisu::expr_t
The possible types of an expression.
"e_" stands for expression.
Enumerator
e_val
e_var
e_op
e_none
Definition at line 14 of file type.h.
op_t
enum tiramisu::op_t
Types of tiramisu operators.
If the expression is of type e_op then it should have an operator type. This is the operator type.
"o_" stands for operator.
Enumerator
o_minus
o_floor
o_sin
o_cos
o_tan
o_asin
o_acos
o_atan
o_abs
o_sqrt
o_expo
o_log
o_ceil
o_round
o_trunc
o_allocate
o_free
o_cast
o_address
o_add
o_sub
o_mul
o_div
o_mod
o_logical_and
o_logical_or
o_logical_not
o_eq
o_ne
o_le
o_lt
o_ge
o_gt
o_max
o_min
o_right_shift
o_left_shift
o_select
o_cond
o_lerp
o_call
o_access
o_none
Definition at line 49 of file type.h.
primitive_t
enum tiramisu::primitive_t
tiramisu data types.
"p_" stands for primitive.
Enumerator
p_uint8
p_uint16
p_uint32
p_uint64
p_int8
p_int16
p_int32
p_int64
p_float32
p_float64
p_boolean
p_none
Definition at line 26 of file type.h.
Function Documentation
generate_new_variable_name()
std::string tiramisu::generate_new_variable_name ()
halide_expr_from_tiramisu_expr()
Halide::Expr tiramisu::halide_expr_from_tiramisu_expr (const tiramisu::computation * comp, std::vector< isl_ast_expr *> & index_expr, const tiramisu::expr & tiramisu_expr)
Convert a Tiramisu expression into a Halide expression.
Referenced by tiramisu::var::var().
halide_pipeline_to_tiramisu_function()
HalideCodegenOutput tiramisu::halide_pipeline_to_tiramisu_function (Halide::Internal::Stmt s, const std::vector< Halide::Internal::Function > & outputs, const std::map< std::string, Halide::Internal::Function > & env, const std::map< std::string, std::vector< int32_t >> & output_buffers_size, tiramisu::function * func)
Referenced by tiramisu::HalideCodegenOutput::HalideCodegenOutput().
halide_stmt_dump()
void tiramisu::halide_stmt_dump (Halide::Internal::Stmt s)
halide_type_from_tiramisu_type()
Halide::Type tiramisu::halide_type_from_tiramisu_type (tiramisu::primitive_t type)
Convert a Tiramisu type into the equivalent Halide type (if it exists), otherwise show an error message (no automatic type conversion is performed).
halide_type_to_tiramisu_type()
tiramisu::primitive_t tiramisu::halide_type_to_tiramisu_type (Halide::Type type)
Convert a Halide type into the equivalent Tiramisu type (if it exists), otherwise show an error message (no automatic type conversion is performed).
loop_level_into_dynamic_dimension()
int tiramisu::loop_level_into_dynamic_dimension (int level)
loop_level_into_static_dimension()
int tiramisu::loop_level_into_static_dimension (int level)
lower_halide_pipeline()
Halide::Module tiramisu::lower_halide_pipeline (const std::string & pipeline_name, const Halide::Target & t, const std::vector< Halide::Argument > & args, const Halide::Internal::LoweredFunc::LinkageType linkage_type, Halide::Internal::Stmt s)
str_from_tiramisu_type_expr()
std::string tiramisu::str_from_tiramisu_type_expr (tiramisu::expr_t type)
Referenced by tiramisu::expr::dump().
str_from_tiramisu_type_primitive()
std::string tiramisu::str_from_tiramisu_type_primitive (tiramisu::primitive_t type)
Referenced by tiramisu::expr::dump().
str_tiramisu_type_op()
std::string tiramisu::str_tiramisu_type_op (tiramisu::op_t type)
Referenced by tiramisu::expr::dump().